# Generated by Django 5.1.1 on 2024-10-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Администратор'), ('content_manager', 'Контента менеджер'), ('opt_manager', 'OPT manager')], max_length=255),
        ),
    ]
