# Generated by Django 5.1.1 on 2024-10-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dvi-slider-images/'),
        ),
    ]
