# Generated by Django 5.1.1 on 2024-10-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0002_mainpageslider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('opt', 'Отдел продаж'), ('employment', 'Отдел трудоустройства')], max_length=255)),
                ('person', models.CharField(max_length=255)),
                ('person_avatar', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255)),
                ('element', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dvi_department_contacts',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
