# Generated by Django 5.1.1 on 2024-10-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0003_departmentcontact_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentcontact',
            name='person_avatar',
            field=models.ImageField(upload_to='dvi/department-contact/'),
        ),
    ]
