# Generated by Django 5.1.1 on 2024-10-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0004_alter_departmentcontact_person_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepartmentContact',
            new_name='Contact',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='dvi_contacts',
        ),
    ]
