# Generated by Django 5.1.1 on 2024-10-16 19:16

import apps.dv_info_site.model_utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0005_rename_departmentcontact_contact_alter_contact_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DVIContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='dvi/content-images/')),
            ],
            options={
                'db_table': 'dvi_content_images',
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('question_ru', models.TextField(null=True)),
                ('question_en', models.TextField(null=True)),
                ('question_zh', models.TextField(null=True)),
                ('question_pt', models.TextField(null=True)),
                ('question_es', models.TextField(null=True)),
                ('question_hi', models.TextField(null=True)),
                ('question_ar', models.TextField(null=True)),
                ('question_kk', models.TextField(null=True)),
                ('question_hy', models.TextField(null=True)),
                ('question_az', models.TextField(null=True)),
                ('question_ro', models.TextField(null=True)),
                ('question_uk', models.TextField(null=True)),
                ('question_ky', models.TextField(null=True)),
                ('question_uz', models.TextField(null=True)),
                ('question_tg', models.TextField(null=True)),
                ('question_tr', models.TextField(null=True)),
                ('question_type', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'form_questions',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_type', models.CharField(choices=[('vacancy', 'Вакансия'), ('partnership', 'Партнерство')], max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'form_templates',
            },
        ),
        migrations.CreateModel(
            name='FormAnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('value_ru', models.TextField(null=True)),
                ('value_en', models.TextField(null=True)),
                ('value_zh', models.TextField(null=True)),
                ('value_pt', models.TextField(null=True)),
                ('value_es', models.TextField(null=True)),
                ('value_hi', models.TextField(null=True)),
                ('value_ar', models.TextField(null=True)),
                ('value_kk', models.TextField(null=True)),
                ('value_hy', models.TextField(null=True)),
                ('value_az', models.TextField(null=True)),
                ('value_ro', models.TextField(null=True)),
                ('value_uk', models.TextField(null=True)),
                ('value_ky', models.TextField(null=True)),
                ('value_uz', models.TextField(null=True)),
                ('value_tg', models.TextField(null=True)),
                ('value_tr', models.TextField(null=True)),
                ('form_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='dv_info_site.formquestion')),
            ],
            options={
                'db_table': 'form_template_answer_choices',
                'ordering': ('created_at',),
                'unique_together': {('form_question', 'value')},
            },
        ),
        migrations.AddField(
            model_name='formquestion',
            name='form_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dv_info_site.formtemplate'),
        ),
        migrations.CreateModel(
            name='FormUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dv_info_site.formtemplate')),
            ],
            options={
                'db_table': 'form_users',
            },
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('file', models.FileField(upload_to=apps.dv_info_site.model_utils.get_form_template_answer_file_path)),
                ('choices', models.ManyToManyField(blank=True, to='dv_info_site.formanswerchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dv_info_site.formquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dv_info_site.formuser')),
            ],
            options={
                'db_table': 'form_answers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='formquestion',
            unique_together={('form_template', 'position')},
        ),
    ]
