# Generated by Django 5.1.1 on 2024-10-17 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0006_dvicontentfile_formquestion_formtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='form_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnerships', to='dv_info_site.formtemplate'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='form_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='dv_info_site.formtemplate'),
        ),
    ]
