# Generated by Django 5.1.1 on 2024-10-17 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0007_partnership_form_template_vacancy_form_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanswer',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_answers', to='dv_info_site.dvicontentfile'),
        ),
        migrations.AlterField(
            model_name='formanswer',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='form_template',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnership', to='dv_info_site.formtemplate'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='form_template',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='dv_info_site.formtemplate'),
        ),
    ]
