# Generated by Django 5.1.1 on 2024-10-17 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0008_alter_formanswer_file_alter_formanswer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanswer',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_answers', to='dv_info_site.dvicontentfile'),
        ),
    ]
