# Generated by Django 5.1.1 on 2024-10-19 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0009_alter_formanswer_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_type', models.CharField(choices=[('input', 'Ввод значения'), ('single_choice', 'Выбор одного из вариантов'), ('multi_choice', 'Выбор нескольких вариантов'), ('input_range', 'Ползунок')], max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('default_value', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('is_required', models.BooleanField(default=True)),
                ('min_value', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('step', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('position', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'calculator_fields',
            },
        ),
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formula', models.TextField(null=True)),
            ],
            options={
                'db_table': 'calculators',
            },
        ),
        migrations.CreateModel(
            name='CalcFieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='dv_info_site.calcfield')),
            ],
            options={
                'db_table': 'calculator_field_items',
            },
        ),
        migrations.AddField(
            model_name='calcfield',
            name='calculator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dv_info_site.calculator'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='calculator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='dv_info_site.calculator'),
        ),
        migrations.AlterUniqueTogether(
            name='calcfield',
            unique_together={('calculator', 'name')},
        ),
    ]
