# Generated by Django 5.1.1 on 2024-10-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0010_calcfield_calculator_calcfieldchoice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='dvicontentfile',
            options={'verbose_name': 'Файл DVI контента', 'verbose_name_plural': 'Файлы DVI контента'},
        ),
        migrations.AlterModelOptions(
            name='dvinstruction',
            options={'verbose_name': 'Инструкция от localhost', 'verbose_name_plural': 'Инструкция от localhost'},
        ),
        migrations.AlterModelOptions(
            name='mainpagebuttonblock',
            options={'verbose_name': 'Блок кнопок главной страницы', 'verbose_name_plural': 'Блок кнопок главной страницы'},
        ),
        migrations.AlterModelOptions(
            name='mainpagereputationlink',
            options={'verbose_name': 'Репутационный ссылки', 'verbose_name_plural': 'Репутационные ссылки'},
        ),
        migrations.AlterModelOptions(
            name='mainpageslider',
            options={'verbose_name': 'Слайдер главной страницы', 'verbose_name_plural': 'Слайдер главной страницы'},
        ),
        migrations.AlterModelOptions(
            name='partnership',
            options={'verbose_name': 'Партнерство'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={'verbose_name': 'Вариация продукта', 'verbose_name_plural': 'Вариации продуктов'},
        ),
        migrations.AlterModelOptions(
            name='productupdatefile',
            options={'verbose_name': 'Файл для обновления продуктов', 'verbose_name_plural': 'Файлы для обновления продуктов'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проекты', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectlink',
            options={'verbose_name': 'Ссылки проекта', 'verbose_name_plural': 'Ссылки проекта'},
        ),
        migrations.AlterModelOptions(
            name='retail',
            options={'verbose_name': 'Розница', 'verbose_name_plural': 'Розница'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансии', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
