# Generated by Django 5.1.1 on 2024-10-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0011_alter_city_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calcfield',
            options={'verbose_name': 'Поле калькулятора', 'verbose_name_plural': 'Поля калькулятора'},
        ),
        migrations.AlterModelOptions(
            name='calcfieldchoice',
            options={'verbose_name': 'Варианты для выбора', 'verbose_name_plural': 'Варианты для выбора'},
        ),
        migrations.AlterModelOptions(
            name='calculator',
            options={'verbose_name': 'Калькулятор вакансии', 'verbose_name_plural': 'Калькулятор вакансии'},
        ),
        migrations.AlterModelOptions(
            name='formquestion',
            options={'ordering': ('position',), 'verbose_name': 'Вопрос анкеты', 'verbose_name_plural': 'Вопросы анкет'},
        ),
        migrations.AlterModelOptions(
            name='formtemplate',
            options={'verbose_name': 'Шаблон анкеты', 'verbose_name_plural': 'Шаблон анкеты'},
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текст'), ('file', 'Файл'), ('file_or_link', 'Файл или ссылка на файл'), ('single_choice', 'Выбор из вариантов'), ('multi_choice', 'Выбор из вариантов')], max_length=255),
        ),
    ]
