# Generated by Django 5.1.1 on 2024-10-31 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0012_alter_calcfield_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formanswer',
            options={'verbose_name': 'Ответы', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='formuser',
            options={'verbose_name': 'Отклик пользователей', 'verbose_name_plural': 'Отклик пользователей'},
        ),
    ]
