# Generated by Django 5.1.1 on 2024-11-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0013_alter_formanswer_options_alter_formuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.ImageField(upload_to='bugreports/')),
            ],
            options={
                'verbose_name': 'Баги',
                'verbose_name_plural': 'Баги',
                'db_table': 'bug_reports',
            },
        ),
        migrations.CreateModel(
            name='BugReportSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_zh', models.CharField(max_length=255, null=True)),
                ('title_pt', models.CharField(max_length=255, null=True)),
                ('title_es', models.CharField(max_length=255, null=True)),
                ('title_hi', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_kk', models.CharField(max_length=255, null=True)),
                ('title_hy', models.CharField(max_length=255, null=True)),
                ('title_az', models.CharField(max_length=255, null=True)),
                ('title_ro', models.CharField(max_length=255, null=True)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_ky', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_tg', models.CharField(max_length=255, null=True)),
                ('title_tr', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Настройки раздела Багов',
                'verbose_name_plural': 'Настройки раздела Багов',
                'db_table': 'bug_report_settings',
            },
        ),
    ]
