# Generated by Django 5.1.1 on 2024-11-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0014_bugreport_bugreportsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugreport',
            options={'ordering': ('-created_at',), 'verbose_name': 'Баги', 'verbose_name_plural': 'Баги'},
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='bugreports/'),
        ),
    ]
