# Generated by Django 5.1.1 on 2024-11-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0015_alter_bugreport_options_alter_bugreport_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageslider',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='description_ar',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='description_az',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='description_en',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='description_es',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='description_hi',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='description_hy',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='description_kk',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='description_ky',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='description_pt',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='description_ro',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='description_ru',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='description_tg',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='description_tr',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='description_uk',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='description_uz',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='description_zh',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
