# Generated by Django 5.1.1 on 2024-11-06 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0016_alter_mainpageslider_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='form_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnerships', to='dv_info_site.formtemplate'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='calculator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='dv_info_site.calculator'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='form_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='dv_info_site.formtemplate'),
        ),
    ]
