# Generated by Django 5.1.1 on 2024-11-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0017_alter_partnership_form_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productupdatefile',
            name='file_type',
            field=models.CharField(choices=[('xlsx', 'XLSX'), ('json', 'JSON')], default='xlsx', max_length=50),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title',
            field=models.CharField(default='Охота на баги', max_length=255),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title_ar',
            field=models.CharField(default='Охота на баги', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title_az',
            field=models.CharField(default='Охота на баги', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title_en',
            field=models.CharField(default='Охота на баги', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title_es',
            field=models.CharField(default='Охота на баги', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title_hi',
            field=models.CharField(default='Охота на баги', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title_hy',
            field=models.CharField(default='Охота на баги', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title_kk',
            field=models.CharField(default='Охота на баги', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title_ky',
            field=models.CharField(default='Охота на баги', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title_pt',
            field=models.CharField(default='Охота на баги', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title_ro',
            field=models.CharField(default='Охота на баги', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title_ru',
            field=models.CharField(default='Охота на баги', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title_tg',
            field=models.CharField(default='Охота на баги', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title_tr',
            field=models.CharField(default='Охота на баги', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title_uk',
            field=models.CharField(default='Охота на баги', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title_uz',
            field=models.CharField(default='Охота на баги', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bugreportsetting',
            name='title_zh',
            field=models.CharField(default='Охота на баги', max_length=255, null=True),
        ),
    ]
