# Generated by Django 5.1.1 on 2024-11-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0018_productupdatefile_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Оффлайн'), ('no_experience', 'Без опыта')], default='online', max_length=50),
        ),
    ]
