# Generated by Django 5.1.1 on 2024-11-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0019_vacancy_work_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='short_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='short_description_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='short_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='short_description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='short_description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='short_description_hy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='short_description_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='short_description_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='short_description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='short_description_ro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='short_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='short_description_tg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='short_description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='short_description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='short_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='short_description_zh',
            field=models.TextField(blank=True, null=True),
        ),
    ]
