# Generated by Django 5.1.1 on 2024-12-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0020_partnership_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='availability_status',
            field=models.CharField(choices=[('preorder', 'Предзаказ'), ('in_stock', 'В наличии')], default='preorder', max_length=20),
        ),
    ]
