# Generated by Django 5.1.1 on 2024-12-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0021_productitem_availability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='availability_status',
            field=models.CharField(choices=[('preorder', 'Предзаказ'), ('in_stock', 'В наличии')], default='preorder', max_length=20, verbose_name='Статус наличия'),
        ),
    ]
