# Generated by Django 5.1.1 on 2024-12-24 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0022_alter_productitem_availability_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description_hi',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description_hy',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description_kk',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description_pt',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description_ro',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description_tg',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description_tr',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='description_zh',
        ),
        migrations.RemoveField(
            model_name='dvinstruction',
            name='icon',
        ),
        migrations.CreateModel(
            name='DVInstructionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1_text', models.TextField(blank=True, null=True)),
                ('column1_text_ru', models.TextField(blank=True, null=True)),
                ('column1_text_en', models.TextField(blank=True, null=True)),
                ('column1_text_zh', models.TextField(blank=True, null=True)),
                ('column1_text_pt', models.TextField(blank=True, null=True)),
                ('column1_text_es', models.TextField(blank=True, null=True)),
                ('column1_text_hi', models.TextField(blank=True, null=True)),
                ('column1_text_ar', models.TextField(blank=True, null=True)),
                ('column1_text_kk', models.TextField(blank=True, null=True)),
                ('column1_text_hy', models.TextField(blank=True, null=True)),
                ('column1_text_az', models.TextField(blank=True, null=True)),
                ('column1_text_ro', models.TextField(blank=True, null=True)),
                ('column1_text_uk', models.TextField(blank=True, null=True)),
                ('column1_text_ky', models.TextField(blank=True, null=True)),
                ('column1_text_uz', models.TextField(blank=True, null=True)),
                ('column1_text_tg', models.TextField(blank=True, null=True)),
                ('column1_text_tr', models.TextField(blank=True, null=True)),
                ('column1_image', models.FileField(blank=True, null=True, upload_to='dvi/dv-icons/')),
                ('column2_text', models.TextField(blank=True, null=True)),
                ('column2_text_ru', models.TextField(blank=True, null=True)),
                ('column2_text_en', models.TextField(blank=True, null=True)),
                ('column2_text_zh', models.TextField(blank=True, null=True)),
                ('column2_text_pt', models.TextField(blank=True, null=True)),
                ('column2_text_es', models.TextField(blank=True, null=True)),
                ('column2_text_hi', models.TextField(blank=True, null=True)),
                ('column2_text_ar', models.TextField(blank=True, null=True)),
                ('column2_text_kk', models.TextField(blank=True, null=True)),
                ('column2_text_hy', models.TextField(blank=True, null=True)),
                ('column2_text_az', models.TextField(blank=True, null=True)),
                ('column2_text_ro', models.TextField(blank=True, null=True)),
                ('column2_text_uk', models.TextField(blank=True, null=True)),
                ('column2_text_ky', models.TextField(blank=True, null=True)),
                ('column2_text_uz', models.TextField(blank=True, null=True)),
                ('column2_text_tg', models.TextField(blank=True, null=True)),
                ('column2_text_tr', models.TextField(blank=True, null=True)),
                ('column2_image', models.FileField(blank=True, null=True, upload_to='dvi/dv-icons/')),
                ('column3_text', models.TextField(blank=True, null=True)),
                ('column3_text_ru', models.TextField(blank=True, null=True)),
                ('column3_text_en', models.TextField(blank=True, null=True)),
                ('column3_text_zh', models.TextField(blank=True, null=True)),
                ('column3_text_pt', models.TextField(blank=True, null=True)),
                ('column3_text_es', models.TextField(blank=True, null=True)),
                ('column3_text_hi', models.TextField(blank=True, null=True)),
                ('column3_text_ar', models.TextField(blank=True, null=True)),
                ('column3_text_kk', models.TextField(blank=True, null=True)),
                ('column3_text_hy', models.TextField(blank=True, null=True)),
                ('column3_text_az', models.TextField(blank=True, null=True)),
                ('column3_text_ro', models.TextField(blank=True, null=True)),
                ('column3_text_uk', models.TextField(blank=True, null=True)),
                ('column3_text_ky', models.TextField(blank=True, null=True)),
                ('column3_text_uz', models.TextField(blank=True, null=True)),
                ('column3_text_tg', models.TextField(blank=True, null=True)),
                ('column3_text_tr', models.TextField(blank=True, null=True)),
                ('column3_image', models.FileField(blank=True, null=True, upload_to='dvi/dv-icons/')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='dv_info_site.dvinstruction')),
            ],
            options={
                'verbose_name': 'Строка инструкции',
                'verbose_name_plural': 'Строки инструкции',
                'db_table': 'dvi_dv_instruction_rows',
            },
        ),
    ]
