# Generated by Django 5.1.1 on 2024-12-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0023_remove_dvinstruction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для покупки'),
        ),
    ]
