# Generated by Django 5.1.1 on 2024-12-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0024_product_buy_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buy_url',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Ссылка для покупки'),
        ),
    ]
