# Generated by Django 5.1.1 on 2025-01-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0025_alter_product_buy_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'dvi_resource_policy',
                'ordering': ('position',),
            },
        ),
    ]
