# Generated by Django 5.1.1 on 2025-01-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0026_resourcepolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcepolicy',
            options={'ordering': ('position',), 'verbose_name': 'Правила и политика ресурса', 'verbose_name_plural': 'Правила и политика ресурса'},
        ),
    ]
