# Generated by Django 5.1.1 on 2025-01-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0027_alter_resourcepolicy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepolicy',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='content_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='content_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='content_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='content_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='content_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='content_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='content_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='content_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='content_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='content_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='content_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='heading_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='heading_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='heading_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='heading_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='heading_hi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='heading_hy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='heading_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='heading_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='heading_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='heading_ro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='heading_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='heading_tg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='heading_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='heading_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='heading_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepolicy',
            name='heading_zh',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
