# Generated by Django 5.1.1 on 2025-02-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_info_site', '0028_resourcepolicy_content_ar_resourcepolicy_content_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_telegram_active',
            field=models.BooleanField(default=True),
        ),
    ]
